### ISSUE TITLE
Logos need exporting

### ISSUE THREAD

**Issue by thomasdavis** [tfrce/stopwatchingus#1]
Someone needs to export all the logos from the designs to the img folder, probably best under a sub folder.

If they are not exportable from the design, I might just start collecting them from the web.

**Comment by pinwale** [comment]
I just added the individual logos to a subfolder in the `img` folder.  I didn't resize them though.

**Comment by thomasdavis** [comment]
I've resized them with css in index.html. they should eventually be resized and exported. Will leave this issue open until I do.
