### ISSUE TITLE
Volunteering page

### ISSUE THREAD

**Issue by sinak** [tfrce/stopwatchingus#52]
Please let us know what you're interested in helping with, and we'll be in touch!

[] Help us with call banking to drive attendance.
[] Help organize transportation to the rally.
[] Hosting a viewing party in your city.

Your name_: ________________
Your email_: ________________
Your phone number_: ________________
Your zipcode_: ________________
Anything else you want to tell us?: ________________

[Submit]

**Comment by BenDoernberg** [comment]
Looks beautiful to me
