### ISSUE TITLE
Lobby day page

### ISSUE THREAD

**Issue by sinak** [tfrce/stopwatchingus#53]
On Friday, October 25th, the day before we rally Washington, we're planning a day of citizen lobbying. 

Schedule:
Morrning - Training event with experts from DC public advocacy organizations
Afternoon - We'll schedule meetings with your representatives in Congress

Sign up:
Your name_: _________________
Your address (line1)_: ______________ \* we need this to find your representatives and schedule meetings
Your Zipcode_: _____________
Your phone number_: ______________
Anything we should know about you? _______________

[Submit]
-> Thanks, we'll be in touch soon!

**Comment by BenDoernberg** [comment]
Looks great!
